### ISSUE TITLE
[Bug] Compatibility Issue - Ultimate Car Mod

### ISSUE THREAD

**Issue by dylanjkl** [Arborsm/ExtraSoundsForge#13]
Suppressed: net.minecraftforge.fml.ModLoadingException: Extra Sounds (extrasounds) encountered an error during the common_setup event phase
 7java.lang.NullPointerException: Registry Object not present: car:canola_oil
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:155) ~[language-java-47.2.2.jar%231182!/:47.2]
		at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:346) ~[core-47.2.2.jar%231181!/:47.2]
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
		at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[core-47.2.2.jar%231181!/:47.2]
		at net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:344) ~[core-47.2.2.jar%231181!/:47.2]
		at net.minecraftforge.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:337) ~[core-47.2.2.jar%231181!/:47.2]
		at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:342) ~[forge-1.20.1-47.1.99-universal.jar%231185!/:?]
		at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.20.1-47.1.99-universal.jar%231185!/:?]
		at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217) ~[core-47.2.2.jar%231181!/:47.2]
		at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209) ~[core-47.2.2.jar%231181!/:47.2]
		at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
		at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:209) ~[core-47.2.2.jar%231181!/:47.2]
		at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[core-47.2.2.jar%231181!/:47.2]
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
		at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[core-47.2.2.jar%231181!/:47.2]
		at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:70) ~[forge-1.20.1-47.1.99-universal.jar%231185!/:?]
		at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:90) ~[forge-1.20.1-47.1.99-universal.jar%231185!/:?]
		at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:70) ~[forge-1.20.1-47.1.99-universal.jar%231185!/:?]
		at net.minecraft.client.Minecraft.<init>(Minecraft.java:459) ~[client-1.20.1-20230612.114412-srg.jar%231180!/:?]
		at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1-forge-47.1.99.jar:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:126) ~[loader-47.2.2.jar:47.2]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:114) ~[loader-47.2.2.jar:47.2]
		at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:24) ~[loader-47.2.2.jar:47.2]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:108) ~[loader-47.2.2.jar:47.2]
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	Caused by: java.lang.NullPointerException: Registry Object not present: car:canola_oil
		at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:572) ~[forge-1.20.1-47.1.99-universal.jar%231185!/:?]
		at de.maxhenkel.car.fluids.FluidCanolaOil.lambda$new$0(FluidCanolaOil.java:14) ~[car-forge-1.20.1-1.0.15.jar%23752!/:1.20.1-1.0.15]
		at net.minecraftforge.fluids.ForgeFlowingFluid.getFluidType(ForgeFlowingFluid.java:63) ~[forge-1.20.1-47.1.99-universal.jar%231185!/:?]
		at net.minecraftforge.fluids.ForgeFlowingFluid.m_142520_(ForgeFlowingFluid.java:151) ~[forge-1.20.1-47.1.99-universal.jar%231185!/:?]
		at org.arbor.extrasounds.mapping.AutoGenerator.autoGenerator(AutoGenerator.java:67) ~[extrasounds-1.2a-1.20.1-forge.jar%23881!/:1.2a-1.20.1-forge]
		at org.arbor.extrasounds.mapping.SoundPackLoader.processSounds(SoundPackLoader.java:143) ~[extrasounds-1.2a-1.20.1-forge.jar%23881!/:1.2a-1.20.1-forge]
		at org.arbor.extrasounds.mapping.SoundPackLoader.init(SoundPackLoader.java:90) ~[extrasounds-1.2a-1.20.1-forge.jar%23881!/:1.2a-1.20.1-forge]
		at org.arbor.extrasounds.mapping.SoundPackLoader.onRegisterEvent(SoundPackLoader.java:55) ~[extrasounds-1.2a-1.20.1-forge.jar%23881!/:1.2a-1.20.1-forge]
		at org.arbor.extrasounds.mapping.__SoundPackLoader_onRegisterEvent_RegisterEvent.invoke(.dynamic) ~[extrasounds-1.2a-1.20.1-forge.jar%23881!/:1.2a-1.20.1-forge]
		at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2389!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2389!/:?]
		at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2389!/:?]
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:151) ~[language-java-47.2.2.jar%231182!/:47.2]

**Comment by Arborsm** [comment]
try this？https://modrinth.com/mod/extrasoundsforge/version/SaUCQMBY
seems curseforge hasn't agreed yet

**Comment by dylanjkl** [comment]
Just tried the replacement, the same error seems to occur on launch.

**Comment by Arborsm** [comment]
> Just tried the replacement, the same error seems to occur on launch.
> 
> I am able to launch with extrasounds-1.1-1.20.1 with no problems though.

hm ok, I will check it later
