### ISSUE TITLE
[1.19.3] Crash on launch, NoSuchMethodError

### ISSUE THREAD

**Issue by satellaview-dev** [Arborsm/ExtraSoundsForge#17]
Tried on 1.2a, b and c. All same result. 
Could be **SoundEvent** hasn't been implemented in FML v44.1.23?

[Possible cause: different implementation / class name in 1.19.3? Linked the 1.19.x sound events page for easy access.](https://docs.minecraftforge.net/en/1.19.x/gameeffects/sounds/#creating-sound-events)

Crash report below,
``` 
-- Head --
Thread: Render thread
Stacktrace:
	at org.arbor.extrasounds.ExtraSounds.<clinit>(ExtraSounds.java:28) ~[extrasounds-1.2b-1.19.2-forge.jar%23518!/:1.2b-1.19.2-forge] {re:classloading}
-- MOD extrasounds --
Details:
	Mod File: <INSTANCE LOCATION>/mods/extrasounds-1.2b-1.19.2-forge.jar
	Failure message: Extra Sounds (extrasounds) has failed to load correctly
		java.lang.NoSuchMethodError: 'void net.minecraft.sounds.SoundEvent.<init>(net.minecraft.resources.ResourceLocation)'
	Mod Version: 1.2b
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'void net.minecraft.sounds.SoundEvent.<init>(net.minecraft.resources.ResourceLocation)'
Stacktrace:
	at org.arbor.extrasounds.ExtraSounds.<clinit>(ExtraSounds.java:28) ~[extrasounds-1.2b-1.19.2-forge.jar%23518!/:1.2b-1.19.2-forge] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.3-44.1.23.jar%23688!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.3-44.1.23.jar%23687!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
```

**Comment by Arborsm** [comment]
oops

**Comment by satellaview-dev** [comment]
Found resource on 1.19.2 -> 1.19.3 SoundEvent changes, [Link](https://gist.github.com/ChampionAsh5357/c21724bafbc630da2ed8899fe0c1d226#soundevent)
I could try to fix this myself, but I wouldn't bet on my java competency. Won't stop me from trying.

**Comment by Arborsm** [comment]
> Found resource on 1.19.2 -> 1.19.3 SoundEvent changes, [Link](https://gist.github.com/ChampionAsh5357/c21724bafbc630da2ed8899fe0c1d226#soundevent)
> I could try to fix this myself, but I wouldn't bet on my java competency. Won't stop me from trying.

try 1.19.4? just change the min mc version in jar

**Comment by satellaview-dev** [comment]
Failed
``	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.23/net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:225)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.23/net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:327)
	at TRANSFORMER/forge@44.1.23/net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:368)
	at TRANSFORMER/forge@44.1.23/net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.23/net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:201)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.23/net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.23/net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:179)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at LAYER PLUGIN/fmlcore@1.19.3-44.1.23/net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179)
	at TRANSFORMER/forge@44.1.23/net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:91)
	at TRANSFORMER/forge@44.1.23/net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:111)
	at TRANSFORMER/forge@44.1.23/net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:91)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.client.Minecraft.<init>(Minecraft.java:469)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.client.main.Main.m_239872_(Main.java:176)
	at TRANSFORMER/minecraft@1.19.3/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.3-44.1.23/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.item.SmithingTemplateItem
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 40 more```

**Comment by satellaview-dev** [comment]
Well, I tried to help fix this, but Java is very confusing to me, so I give up. Hope you can get this working, the mod seems really cool!
