### ISSUE TITLE
Ad Astra Giselle Incompatibility - Crash on launch

### ISSUE THREAD

**Issue by dylanjkl** [Arborsm/ExtraSoundsForge#8]
net.minecraftforge.fml.ModLoadingException: Extra Sounds (extrasounds) encountered an error during the common_setup event phase
§7java.lang.NullPointerException: Registry Object not present: ad_astra_giselle_addon:space_breathing_unit
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[language-java-47.1.47.jar%231166!/:47.1] {}
		at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrapInModOrder$33(ModLoader.java:346) ~[core-47.1.47.jar%231165!/:47.1] {}
		at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.ModList.forEachModInOrder(ModList.java:227) ~[core-47.1.47.jar%231165!/:47.1] {re:mixin}
		at net.minecraftforge.fml.ModLoader.postEventWithWrapInModOrder(ModLoader.java:344) ~[core-47.1.47.jar%231165!/:47.1] {}
		at net.minecraftforge.fml.ModLoader.postEventWrapContainerInModOrder(ModLoader.java:337) ~[core-47.1.47.jar%231165!/:47.1] {}
		at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:342) ~[forge-1.20.1-47.1.97-universal.jar%231169!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-
 

The root cause seems to be a NullPointerException related to a missing registry object: ad_astra_giselle_addon:space_breathing_unit. This suggests that the Extra Sounds is expecting an item or block (in this case, a "space breathing unit") to be present, which is likely provided by the Ad Astra Giselle Addon mod or a similar mod, but it cannot find it.

**Comment by Arborsm** [comment]
as I know seems Ad Astra Giselle Addon not support the latest adastra, and could you send me the whole debug.log?

**Comment by Arborsm** [comment]
#9
